general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = true
}

# 🖼️ Background
background {
    monitor =
    path = /home/asitos/Downloads/wallpapers/xas2ko-cinamoroll-wallpaper.jpg   # <--- CHANGE THIS
    color = rgba(25, 20, 20, 1.0)
    blur_passes = 2 # 0 disables blurring
    blur_size = 7
}

# 🕰️ Time
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(180, 190, 254, 1.0) # Lavender
    font_size = 120
    font_family = JetBrains Mono Nerd Font
    position = 0, -300
    halign = center
    valign = top
}

# 📅 Date
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %d %B %Y")"
    color = rgba(205, 214, 244, 1.0)
    font_size = 30
    font_family = JetBrains Mono Nerd Font
    position = 0, -500
    halign = center
    valign = top
}

# 🔒 Input Field (The Cute Part)
input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(180, 190, 254, 1.0) # Lavender Border
    inner_color = rgba(30, 30, 46, 1.0)    # Dark Background
    font_color = rgba(205, 214, 244, 1.0)
    fade_on_empty = false
    placeholder_text = <i>Password pookie? 🥺</i> # <--- CUTE TEXT
    hide_input = false
    position = 0, -20
    halign = center
    val
