# GENERAL
general {
    no_fade_in = true
    no_fade_out = true
    disable_loading_bar = true
    hide_cursor = true
    immediate_render = true
}

# BACKGROUND
background {
    monitor =
    path = ~/Downloads/wallpapers/omori.jpg
    color = rgb(0, 0, 0)
    blur_passes = 1
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.8916
    vibrancy_darkness = 0.0
}

# Day-Month-Date
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %B %d - %I:%M")"
    color = rgb(200, 200, 200)
    font_size = 15
    font_family = Sans
    position = 0, 250
    halign = center
    valign = center
}

# Authenticate outer box
shape {
    monitor =
    size = 500, 140
    color = rgba(0, 0, 0, 0)
    rounding = 0
    border_size = 2
    border_color = rgba(255, 255, 255, 1)
    rotate = 0
    position = 0, 0
    halign = center
    valign = center
}

# USER-BOX Header Background
shape {
    monitor =
    size = 60, 24
    color = rgb(0, 0, 0)
    rounding = 0
    border_size = 2
    border_color = rgb(0, 0, 0)
    rotate = 0
    position = -220, 70
    halign = center
    valign = center
    zindex = 5
}

# Header Label
label {
    monitor =
    text = login
    color = rgba(216, 222, 233, 0.80)
    font_size = 11
    font_family = Sans
    position = -220, 70
    halign = center
    valign = center
    zindex = 6
}

# Username Label
label {
    monitor =
    text = <b>username:                           $USER</b>
    color = rgba(216, 222, 233, 0.80)
    font_size = 11
    font_family = Sans
    position = -120, 20
    halign = center
    valign = center
    zindex = 1
}

# Password Label
label {
    monitor =
    text = <b>password:</b>
    color = rgba(216, 222, 233, 0.80)
    font_size = 11
    font_family = Sans
    position = -150, -20
    halign = center
    valign = center
    zindex = 5
}

# INPUT FIELD
input-field {
    monitor =
    size = 200, 36
    outline_thickness = 1
    dots_size = 0.25
    dots_spacing = 0.3
    dots_center = true
    outer_color = rgba(255, 255, 255, 0.2)
    inner_color = rgba(0, 0, 0, 0.5)
    font_color = rgb(255, 255, 255)
    fade_on_empty = false
    placeholder_text =
    hide_input = false
    position = 00, -20
    halign = center
    valign = center
}

# NOTIFICATION
label {
    monitor =
    text =
    color = rgba(255, 255, 255, 0.90)
    font_size = 14
    font_family = Sans
    position = 0, 180
    halign = center
    valign = center
    zindex = 10
}
