# Wallpaper ko memory mein load karein
preload = /home/asitos/Downloads/milkwallpaper.jpg

# Monitor par wallpaper set karein
# Aapka monitor 'preferred' set hai config mein
wallpaper = /home/asitos/Downloads/milkwallpaper.jpg

# Niche wala text (splash) hatane ke liye
splash = false
