#!/usr/bin/env bash

# 1. Select region (slurp)
# 2. Screenshot region to RAM (grim)
# 3. Extract text (tesseract)
# 4. Copy to Clipboard (wl-copy)

grim -g "$(slurp)" - | tesseract stdin stdout | wl-copy

# Optional: Send a notification so you know it worked
notify-send "OCR" "Text copied to clipboard."
